package mx.tec.alarmate.puzzle

const val ARG_PUZZLE = "ARG_PUZZLE"
const val ARG_ALARM = "ARG_ALARM"
const val ARG_PUZZLE_ALARM_ID = "ARG_PUZZLE_ALARM_ID"

const val INTERVAL_TIME_SLOW = 1000L
const val INTERVAL_TIME_NORMAL = 500L
const val INTERVAL_TIME_FAST = 250L

const val ANIMATING_INTERVAL_TIME = 1000L

val MY_PERMISSIONS_REQUEST_CAMERA = 1